[versions]

kotlin = "2.3.0"
sqlDelight = "2.2.1"
agp = "8.13.2"
compose = "1.9.3"
activityCompose = "1.12.2"
coroutines = "1.10.2"
serialization = "1.9.0"
mviKotlin = "3.3.0" # 4.3.0 has breaking changes
decompose = "2.1.4-compose-experimental" # later versions have breaking changes
essenty = "1.2.0" # 2.5.0 has breaking changes
ktor = "2.3.6" # 3.3.2 has breaking changes
koin = "4.1.1"
imageLoader = "1.7.1" # 1.10.0 has breaking changes
touchlab = "2.0.5" # 2.1.0 has breaking changes
compose-hot-reload = "1.0.0"

[libraries]
activityCompose = { group =  "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
coroutinesCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
decompose = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decompose" }
decompose-extensionsCompose = { group = "com.arkivanov.decompose", name = "extensions-compose-jetbrains", version.ref = "decompose" }
essenty-lifecycle = { group = "com.arkivanov.essenty", name = "lifecycle", version.ref = "essenty" }
imageLoader = { group =  "io.github.qdsfdhvh", name = "image-loader", version.ref = "imageLoader" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
kotlinxSerializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutines" }
ktor-clientCore = { group =  "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-serializationKotlinxJson = { group =  "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-clientContentNegotiation = { group =  "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-clientLogging = { group =  "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
# Engines
ktor-clientAndroid = { group =  "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-clientDarwin = { group =  "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-clientJava = { group =  "io.ktor", name = "ktor-client-java", version.ref = "ktor" }
mvikotlin = { group = "com.arkivanov.mvikotlin", name = "mvikotlin", version.ref = "mviKotlin" }
mvikotlinMain = { group = "com.arkivanov.mvikotlin", name = "mvikotlin-main", version.ref = "mviKotlin" }
mvikotlinExtensionsCoroutines = { group = "com.arkivanov.mvikotlin", name = "mvikotlin-extensions-coroutines", version.ref = "mviKotlin" }
sqlDelight-androidDriver = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqlDelight" }
sqlDelight-sqliteDriver = { group = "app.cash.sqldelight", name = "sqlite-driver", version.ref = "sqlDelight" }
sqlDelight-nativeDriver = { group = "app.cash.sqldelight", name = "native-driver", version.ref = "sqlDelight" }
sqlDelight-coroutinesExtensions = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sqlDelight" }
sqlDelight-primitiveAdapters = { group = "app.cash.sqldelight", name = "primitive-adapters", version.ref = "sqlDelight" }
statelyCommon = { group = "co.touchlab", name = "stately-common", version.ref = "touchlab" }

[plugins]
sqlDelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-native-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hot-reload" }
